import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { ThemeToggle } from "@/components/theme-toggle";
import {
  ArrowRight,
  Cookie,
  Database,
  FileText,
  Globe,
  Lock,
  Mail,
  ShieldCheck,
} from "lucide-react";

const UPDATED_AT = "June 1, 2026";

const SUMMARY_ITEMS = [
  {
    title: "Data handled",
    description:
      "Admin credentials, API key hashes, Roblox transactions, Discord webhook URL, session cookie.",
    icon: Database,
  },
  {
    title: "Purposes",
    description:
      "Authentication, security, Discord notifications, analytics, and abuse prevention.",
    icon: ShieldCheck,
  },
  {
    title: "Sharing",
    description:
      "Discord (webhook), Turso (database), Vercel/hosting (infrastructure logs).",
    icon: Globe,
  },
  {
    title: "Privacy contact",
    description:
      "Project maintainer: devmirkoo@gmail.com • Telegram/Discord: @devmirko",
    icon: Mail,
  },
];

const DATA_ROWS = [
  {
    category: "Admin account",
    details: ["username", "password hash (bcrypt)", "admin id", "created_at"],
    source: "Entered by the administrator",
    purpose:
      "Create and authenticate the admin account and secure dashboard access.",
  },
  {
    category: "Session and cookies",
    details: [
      "rdb_session cookie (JWT with adminId and username)",
      "24h expiration",
    ],
    source: "Generated by the server",
    purpose: "Maintain admin sessions and protect restricted routes.",
  },
  {
    category: "API keys",
    details: [
      "label",
      "SHA-256 hash",
      "created_at",
      "revoked status",
      "raw key shown once",
    ],
    source: "Generated in the admin dashboard",
    purpose:
      "Authenticate game server requests and allow key revocation.",
  },
  {
    category: "Roblox transactions",
    details: [
      "userId",
      "productId",
      "gamepassId (optional)",
      "isAGift",
      "gifterId (optional)",
      "amount",
      "universeId",
      "placeId",
      "transactionId",
      "timestamp",
      "itemType",
      "created_at",
    ],
    source: "Roblox game servers via API",
    purpose:
      "Record purchases, display analytics, and send Discord notifications.",
  },
  {
    category: "Discord webhook",
    details: ["webhook URL", "test timestamp", "delivery status"],
    source: "Entered by the administrator",
    purpose: "Send real-time purchase notifications to Discord.",
  },
  {
    category: "Technical data",
    details: [
      "IP address (rate limiting)",
      "request headers",
      "hosting logs",
    ],
    source: "Collected automatically",
    purpose: "Security, abuse prevention, and technical troubleshooting.",
  },
];

const RIGHTS = [
  "Access to personal data and a copy of the data",
  "Correction of inaccurate information",
  "Deletion or restriction of processing",
  "Data portability",
  "Opt-out of marketing (if enabled)",
  "Lodge a complaint with a supervisory authority",
];

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen grid-noise">
      <nav className="fixed top-0 left-0 right-0 z-50 glass border-b border-border">
        <div className="mx-auto max-w-6xl flex items-center justify-between px-6 h-14">
          <div className="flex items-center gap-2">
            <div
              className="size-7 bg-primary"
              style={{
                maskImage: "url(/logo.svg)",
                maskSize: "contain",
                maskRepeat: "no-repeat",
                maskPosition: "center",
                WebkitMaskImage: "url(/logo.svg)",
                WebkitMaskSize: "contain",
                WebkitMaskRepeat: "no-repeat",
                WebkitMaskPosition: "center",
              }}
            />
            <span className="font-semibold text-sm tracking-tight">Hoorks</span>
          </div>
          <div className="flex items-center gap-1">
            <Link href="/">
              <Button variant="ghost" size="sm">
                Home
              </Button>
            </Link>
            <Link href="/docs">
              <Button variant="ghost" size="sm">
                Docs
              </Button>
            </Link>
            <Link href="/terms">
              <Button variant="ghost" size="sm">
                Terms
              </Button>
            </Link>
            <Link href="/privacy">
              <Button variant="secondary" size="sm">
                Privacy
              </Button>
            </Link>
            <ThemeToggle />
            <Link href="/admin">
              <Button size="sm">
                Admin
                <ArrowRight data-icon="inline-end" />
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      <main className="pt-24 pb-20 px-6">
        <div className="mx-auto max-w-6xl">
          <div className="flex flex-col gap-4 mb-10 animate-fade-in">
            <Badge variant="outline" className="w-fit border-primary/30 text-primary">
              Privacy Policy • Last updated: {UPDATED_AT}
            </Badge>
            <h1 className="text-4xl md:text-5xl font-bold tracking-tight">
              Hoorks Privacy Policy
            </h1>
            <p className="text-lg text-muted-foreground max-w-3xl">
              This policy explains what data Hoorks collects, why it is needed,
              and how it is used to connect Roblox servers with Discord securely.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr] gap-10">
            <aside className="flex flex-col gap-6 lg:sticky lg:top-24 h-fit">
              <Card className="glow-border">
                <CardHeader>
                  <CardTitle className="text-sm uppercase tracking-wide text-muted-foreground">
                    Part 1 • Summary
                  </CardTitle>
                </CardHeader>
                <CardContent className="flex flex-col gap-4">
                  {SUMMARY_ITEMS.map((item) => {
                    const Icon = item.icon;
                    return (
                      <div key={item.title} className="flex gap-3">
                        <div className="flex size-9 items-center justify-center rounded-lg bg-primary/10">
                          <Icon className="text-primary size-4" />
                        </div>
                        <div>
                          <div className="text-sm font-semibold">{item.title}</div>
                          <p className="text-xs text-muted-foreground leading-relaxed">
                            {item.description}
                          </p>
                        </div>
                      </div>
                    );
                  })}
                </CardContent>
              </Card>

              <Card className="glow-border">
                <CardHeader>
                  <CardTitle className="text-sm uppercase tracking-wide text-muted-foreground">
                    Quick index
                  </CardTitle>
                </CardHeader>
                <CardContent className="text-sm text-muted-foreground flex flex-col gap-2">
                  {[
                    { href: "#summary", label: "Part 1: Summary" },
                    { href: "#policy", label: "Part 2: Full policy" },
                    { href: "#notes", label: "Part 3: Compliance notes" },
                    { href: "#data", label: "Data collected" },
                    { href: "#use", label: "How we use data" },
                    { href: "#sharing", label: "Sharing" },
                    { href: "#rights", label: "Rights" },
                    { href: "#cookies", label: "Cookies" },
                  ].map((item) => (
                    <a
                      key={item.href}
                      href={item.href}
                      className="hover:text-foreground transition-colors"
                    >
                      {item.label}
                    </a>
                  ))}
                </CardContent>
              </Card>
            </aside>

            <div className="flex flex-col gap-12">
              <section id="summary" className="scroll-mt-24">
                <div className="flex items-center gap-2 mb-3">
                  <FileText className="text-primary size-5" />
                  <h2 className="text-2xl font-semibold">Part 1: Summary</h2>
                </div>
                <p className="text-muted-foreground leading-relaxed">
                  Hoorks collects only the data required to authenticate administrators,
                  record Roblox purchase events, and send notifications to Discord.
                  We do not collect payment card data, bank details, or player emails.
                </p>
              </section>

              <section id="policy" className="scroll-mt-24">
                <div className="flex items-center gap-2 mb-3">
                  <Database className="text-primary size-5" />
                  <h2 className="text-2xl font-semibold">
                    Part 2: Full privacy policy
                  </h2>
                </div>

                <div className="flex flex-col gap-8">
                  <div id="data" className="scroll-mt-24">
                    <h3 className="text-lg font-semibold mb-3">1. Information we collect</h3>
                    <div className="rounded-xl border border-border bg-card/50 overflow-hidden">
                      <div className="overflow-auto">
                        <table className="min-w-full text-sm">
                          <thead className="bg-muted/40 text-muted-foreground">
                            <tr>
                              <th className="px-4 py-3 text-left font-medium">Category</th>
                              <th className="px-4 py-3 text-left font-medium">Specific data</th>
                              <th className="px-4 py-3 text-left font-medium">Source</th>
                              <th className="px-4 py-3 text-left font-medium">Purpose</th>
                            </tr>
                          </thead>
                          <tbody>
                            {DATA_ROWS.map((row) => (
                              <tr key={row.category} className="border-t border-border">
                                <td className="px-4 py-3 font-medium">{row.category}</td>
                                <td className="px-4 py-3">
                                  <div className="flex flex-col gap-1 text-xs text-muted-foreground">
                                    {row.details.map((detail) => (
                                      <span key={detail}>{detail}</span>
                                    ))}
                                  </div>
                                </td>
                                <td className="px-4 py-3 text-muted-foreground text-xs">
                                  {row.source}
                                </td>
                                <td className="px-4 py-3 text-muted-foreground text-xs">
                                  {row.purpose}
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                    <p className="mt-3 text-xs text-muted-foreground">
                      Note: Hoorks does not request player emails, payment cards, or sensitive
                      personal data.
                    </p>
                  </div>

                  <div id="collection">
                    <h3 className="text-lg font-semibold mb-3">2. How we collect data</h3>
                    <p className="text-muted-foreground leading-relaxed">
                      Data comes from three sources: (1) administrator input in the dashboard
                      (setup, login, API keys, webhook), (2) purchase events sent by Roblox
                      game servers through the Hoorks API, and (3) technical data collected
                      automatically by the hosting infrastructure for security and stability.
                    </p>
                  </div>

                  <div id="use" className="scroll-mt-24">
                    <h3 className="text-lg font-semibold mb-3">3. How we use data</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {[
                        {
                          title: "Service delivery",
                          description:
                            "Record transactions, display dashboard analytics, and notify Discord.",
                        },
                        {
                          title: "Security",
                          description:
                            "Protect API routes with hashed keys, JWTs, and rate limiting.",
                        },
                        {
                          title: "Support and debugging",
                          description:
                            "Resolve technical issues and monitor system health.",
                        },
                        {
                          title: "Compliance",
                          description:
                            "Meet legal obligations and respond to data requests where required.",
                        },
                      ].map((item) => (
                        <Card key={item.title} className="glow-border">
                          <CardHeader>
                            <CardTitle className="text-sm">{item.title}</CardTitle>
                          </CardHeader>
                          <CardContent className="text-xs text-muted-foreground">
                            {item.description}
                          </CardContent>
                        </Card>
                      ))}
                    </div>
                  </div>

                  <div id="legal-basis">
                    <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                      4. Legal basis for processing
                      <Badge variant="destructive">[⚠️ LEGAL REVIEW REQUIRED]</Badge>
                    </h3>
                    <p className="text-muted-foreground leading-relaxed">
                      Typical legal bases include contract performance (providing the service),
                      legal obligations, legitimate interests (security), and consent for any
                      non-essential processing. Confirm the applicable basis with legal counsel.
                    </p>
                  </div>

                  <div id="sharing" className="scroll-mt-24">
                    <h3 className="text-lg font-semibold mb-3">5. Sharing and third parties</h3>
                    <div className="flex flex-col gap-3 text-muted-foreground text-sm">
                      <p>
                        We share data only with providers required to operate the service:
                      </p>
                      <ul className="list-disc list-inside space-y-2">
                        <li>
                          <span className="font-medium text-foreground">Discord</span>:
                          receives purchase data through webhooks.
                        </li>
                        <li>
                          <span className="font-medium text-foreground">Turso (libSQL)</span>:
                          hosts the database containing accounts, keys, and transactions.
                        </li>
                        <li>
                          <span className="font-medium text-foreground">Vercel/hosting</span>:
                          runs the infrastructure and may generate technical logs.
                        </li>
                      </ul>
                      <p>
                        We do not sell personal data and do not share data for advertising.
                      </p>
                    </div>
                  </div>

                  <div id="transfers">
                    <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                      6. International data transfers
                      <Badge variant="destructive">[⚠️ LEGAL REVIEW REQUIRED]</Badge>
                    </h3>
                    <p className="text-muted-foreground leading-relaxed">
                      Data may be processed in regions outside a user location depending on
                      provider infrastructure. Ensure appropriate transfer mechanisms
                      (e.g. SCCs) if GDPR applies.
                    </p>
                  </div>

                  <div id="retention">
                    <h3 className="text-lg font-semibold mb-3">7. Data retention</h3>
                    <div className="flex flex-col gap-3 text-muted-foreground">
                      <p>
                        Hoorks retains data for as long as it is needed to provide the service:
                      </p>
                      <ul className="list-disc list-inside space-y-2 text-sm">
                        <li>Admin data and API keys: until revoked or removed.</li>
                        <li>Transactions: retained until removed by the administrator.</li>
                        <li>Discord webhook: stored until replaced or removed.</li>
                        <li>Rate-limit IP data: stored in memory for the window duration.</li>
                      </ul>
                      <p className="text-xs text-muted-foreground">
                        [⚠️ LEGAL REVIEW REQUIRED] Define exact retention periods based on
                        jurisdiction and tax obligations.
                      </p>
                    </div>
                  </div>

                  <div id="rights" className="scroll-mt-24">
                    <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                      8. User rights
                      <Badge variant="destructive">[⚠️ LEGAL REVIEW REQUIRED]</Badge>
                    </h3>
                    <p className="text-muted-foreground leading-relaxed">
                      Depending on jurisdiction, users may have the right to:
                    </p>
                    <ul className="mt-3 list-disc list-inside space-y-2 text-sm text-muted-foreground">
                      {RIGHTS.map((right) => (
                        <li key={right}>{right}</li>
                      ))}
                    </ul>
                    <p className="mt-3 text-sm text-muted-foreground">
                      Requests can be sent to:{" "}
                      <span className="text-foreground">devmirkoo@gmail.com</span> or{" "}
                      <span className="text-foreground">@devmirko</span> on Telegram or Discord.
                    </p>
                  </div>

                  <div id="cookies" className="scroll-mt-24">
                    <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                      9. Cookies and tracking
                      <Cookie className="size-4 text-primary" />
                    </h3>
                    <p className="text-muted-foreground leading-relaxed">
                      We use only a HTTP-only session cookie (
                      <code className="font-mono text-xs">rdb_session</code>) to keep
                      admin sessions active. We do not use advertising or profiling cookies.
                    </p>
                  </div>

                  <div id="security">
                    <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                      10. Security
                      <Lock className="size-4 text-primary" />
                    </h3>
                    <p className="text-muted-foreground leading-relaxed">
                      Data is protected with credential hashing, signed JWTs, SHA-256 API keys,
                      and rate limiting. No system is fully secure, but we apply reasonable
                      safeguards to reduce risk.
                    </p>
                  </div>

                  <div id="children">
                    <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
                      11. Children&apos;s privacy
                      <Badge variant="destructive">[⚠️ LEGAL REVIEW REQUIRED]</Badge>
                    </h3>
                    <p className="text-muted-foreground leading-relaxed">
                      Hoorks is intended for server operators and is not designed for direct
                      use by children. Confirm any COPPA or local obligations if minors are involved.
                    </p>
                  </div>

                  <div id="contact">
                    <h3 className="text-lg font-semibold mb-3">12. Contact</h3>
                    <p className="text-muted-foreground leading-relaxed">
                      Privacy contact: <span className="text-foreground">devmirkoo@gmail.com</span>.
                      Telegram or Discord: <span className="text-foreground">@devmirko</span>.
                    </p>
                  </div>

                  <div id="changes">
                    <h3 className="text-lg font-semibold mb-3">13. Policy changes</h3>
                    <p className="text-muted-foreground leading-relaxed">
                      If we make material changes, we will provide notice in the dashboard
                      or via official project channels.
                    </p>
                  </div>
                </div>
              </section>

              <Separator />

              <section id="notes" className="scroll-mt-24">
                <div className="flex items-center gap-2 mb-3">
                  <FileText className="text-primary size-5" />
                  <h2 className="text-2xl font-semibold">
                    Part 3: Customization and compliance notes
                  </h2>
                </div>
                <Card className="glow-border">
                  <CardHeader>
                    <CardTitle className="text-sm uppercase tracking-wide text-muted-foreground">
                      Operational checklist
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="text-sm text-muted-foreground flex flex-col gap-3">
                    <p className="font-medium text-foreground">
                      [⚠️ LEGAL REVIEW REQUIRED] Complete these items before publishing:
                    </p>
                    <ul className="list-disc list-inside space-y-2">
                      <li>Add the legal entity name and address if applicable.</li>
                      <li>Confirm applicable jurisdictions (GDPR, CCPA/CPRA, etc.).</li>
                      <li>Define exact retention periods for each data category.</li>
                      <li>Set a process for access and deletion requests.</li>
                      <li>Sign DPAs with providers (Turso, Vercel, Discord).</li>
                      <li>Update the cookie section if analytics or marketing are added.</li>
                    </ul>
                    <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-xs text-destructive">
                      This policy is an informational draft and requires legal review
                      before publication.
                    </div>
                  </CardContent>
                </Card>
              </section>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
